//! The authored row groups the Brutal preset collapses onto a type's top row.
//!
//! The disc cannot express this grouping: the three patchable columns carry
//! numbers, not type identity, and the `MODEL` column the game uses to tell
//! rows apart exists only at runtime (spec §12). The table below came from a
//! RAM snapshot of the authored table, via `tools/rowgroups.py`; the tests
//! check it against that snapshot and against the clean ISO's HP column. That
//! these groups are the game's real type partition cannot be proved from the
//! disc alone, and the About panel states it as inferred (spec §12.3, §12.5).
//!
//! No game data is stored here — row indices and model names only.

use std::ops::RangeInclusive;

/// Rows the collapse never writes: the practice stage's own lesson rows and its
/// 2-player graduation tripwire (spec §12.2, §3.6).
pub const COLLAPSE_SKIP_ROWS: RangeInclusive<usize> = 638..=645;

/// One enemy model's authored rows. `top` is the row with the maximum authored
/// HP, which is the row the collapse copies over the group's other rows
/// (spec §12.1).
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct RowGroup {
    pub model: &'static str,
    pub top: usize,
    pub rows: &'static [usize],
}

/// All 48 groups — 39 enemy types and 9 `g_*` props — covering the 580 live
/// rows of the 649-row table. Generated by `tools/rowgroups.py`; do not edit by
/// hand. Ordered by first row.
pub const ROW_GROUPS: &[RowGroup] = &[
    RowGroup {
        model: "e_goburi",
        top: 393,
        rows: &[
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388,
            389, 390, 391, 392, 393, 638, 639,
        ],
    },
    RowGroup {
        model: "e_nume",
        top: 637,
        rows: &[
            12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 448, 449, 450, 451, 452, 453, 636, 637,
            642, 643,
        ],
    },
    RowGroup {
        model: "e_scum",
        top: 32,
        rows: &[
            24, 25, 26, 27, 28, 29, 30, 31, 32, 454, 455, 456, 457, 458, 459,
        ],
    },
    RowGroup {
        model: "e_ogre",
        top: 41,
        rows: &[33, 34, 35, 36, 37, 38, 39, 40, 41, 460, 461, 462, 640, 641],
    },
    RowGroup {
        model: "e_mecha1",
        top: 56,
        rows: &[
            42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 463, 464, 465, 466, 467,
            468,
        ],
    },
    RowGroup {
        model: "e_mecha4",
        top: 73,
        rows: &[
            57, 58, 59, 60, 61, 62, 63, 64, 65, 67, 70, 73, 469, 470, 471, 472, 473, 474, 475, 476,
            477,
        ],
    },
    RowGroup {
        model: "e_mecha4bs",
        top: 74,
        rows: &[68, 71, 74],
    },
    RowGroup {
        model: "e_blosso",
        top: 88,
        rows: &[76, 78, 80, 82, 85, 88],
    },
    RowGroup {
        model: "e_cockatri",
        top: 95,
        rows: &[91, 93, 95, 644, 645],
    },
    RowGroup {
        model: "e_mammos",
        top: 104,
        rows: &[97, 98, 100, 101, 103, 104],
    },
    RowGroup {
        model: "f_apocaly",
        top: 112,
        rows: &[106, 109, 112],
    },
    RowGroup {
        model: "e_mummy",
        top: 408,
        rows: &[
            114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 394, 395, 396, 397, 398,
            399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 478, 479, 480, 481, 482, 483, 484,
            485, 486, 487, 488, 489,
        ],
    },
    RowGroup {
        model: "e_mecha2",
        top: 624,
        rows: &[
            126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
            143, 144, 145, 146, 147, 148, 149, 490, 491, 492, 610, 611, 612, 613, 614, 615, 616,
            617, 618, 619, 620, 621, 622, 623, 624,
        ],
    },
    RowGroup {
        model: "e_tyrano",
        top: 158,
        rows: &[150, 151, 152, 153, 154, 155, 156, 157, 158],
    },
    RowGroup {
        model: "e_minotaru",
        top: 167,
        rows: &[
            159, 160, 161, 162, 163, 164, 165, 166, 167, 493, 494, 495, 496, 497, 498,
        ],
    },
    RowGroup {
        model: "e_pharaoh",
        top: 176,
        rows: &[
            168, 169, 170, 171, 172, 173, 174, 175, 176, 499, 500, 501, 502, 503, 504, 505, 506,
            507, 508, 509, 510,
        ],
    },
    RowGroup {
        model: "e_arachne",
        top: 182,
        rows: &[178, 180, 182],
    },
    RowGroup {
        model: "e_skulgrey",
        top: 522,
        rows: &[
            183, 184, 185, 187, 190, 193, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521,
            522,
        ],
    },
    RowGroup {
        model: "e_anomalo",
        top: 203,
        rows: &[196, 197, 199, 200, 202, 203],
    },
    RowGroup {
        model: "f_belvam",
        top: 211,
        rows: &[205, 208, 211],
    },
    RowGroup {
        model: "e_otama",
        top: 423,
        rows: &[
            213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 409, 410, 411, 412, 413,
            414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 523, 524, 525, 526,
            527, 528, 529, 530, 531, 532, 533, 534,
        ],
    },
    RowGroup {
        model: "e_geko",
        top: 432,
        rows: &[
            225, 226, 227, 228, 229, 230, 231, 232, 233, 427, 428, 429, 430, 431, 432, 535, 536,
            537, 538, 539, 540, 541, 542, 543, 544, 545, 546,
        ],
    },
    RowGroup {
        model: "e_torta",
        top: 242,
        rows: &[234, 235, 236, 237, 238, 239, 240, 241, 242],
    },
    RowGroup {
        model: "e_maridevi",
        top: 251,
        rows: &[
            243, 244, 245, 246, 247, 248, 249, 250, 251, 547, 548, 549, 550, 551, 552, 553, 554,
            555, 556, 557, 558,
        ],
    },
    RowGroup {
        model: "e_mecha3",
        top: 648,
        rows: &[
            252, 253, 254, 255, 256, 257, 258, 260, 261, 262, 263, 264, 265, 266, 268, 269, 270,
            271, 272, 273, 274, 630, 631, 632, 646, 647, 648,
        ],
    },
    RowGroup {
        model: "e_tonogeko",
        top: 570,
        rows: &[
            276, 277, 278, 280, 281, 283, 284, 286, 287, 559, 560, 561, 562, 563, 564, 565, 566,
            567, 568, 569, 570,
        ],
    },
    RowGroup {
        model: "e_diabolo",
        top: 295,
        rows: &[289, 292, 295],
    },
    RowGroup {
        model: "f_luce",
        top: 304,
        rows: &[298, 301, 304],
    },
    RowGroup {
        model: "e_infermo",
        top: 444,
        rows: &[
            306, 307, 308, 309, 310, 311, 312, 313, 314, 439, 440, 441, 442, 443, 444, 571, 572,
            573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 627, 628, 629,
        ],
    },
    RowGroup {
        model: "e_megadra",
        top: 323,
        rows: &[
            315, 316, 317, 318, 319, 320, 321, 322, 323, 445, 446, 447, 583, 584, 585, 586, 587,
            588, 589, 590, 591, 592, 593, 594,
        ],
    },
    RowGroup {
        model: "e_rare",
        top: 332,
        rows: &[
            324, 325, 326, 327, 328, 329, 330, 331, 332, 595, 596, 597, 598, 599, 600, 601, 602,
            603, 604, 605, 606,
        ],
    },
    RowGroup {
        model: "e_impdra",
        top: 338,
        rows: &[333, 334, 335, 336, 337, 338],
    },
    RowGroup {
        model: "e_mecha5",
        top: 345,
        rows: &[339, 340, 341, 342, 343, 344, 345, 346, 347],
    },
    RowGroup {
        model: "e_ldknight",
        top: 609,
        rows: &[348, 349, 350, 351, 352, 353, 354, 355, 356, 607, 608, 609],
    },
    RowGroup {
        model: "f_devl1b",
        top: 359,
        rows: &[357, 358, 359],
    },
    RowGroup {
        model: "f_devl1",
        top: 362,
        rows: &[360, 361, 362],
    },
    RowGroup {
        model: "f_devl22",
        top: 365,
        rows: &[363, 364, 365],
    },
    RowGroup {
        model: "f_devl3",
        top: 368,
        rows: &[366, 367, 368],
    },
    RowGroup {
        model: "g_box",
        top: 370,
        rows: &[370],
    },
    RowGroup {
        model: "g_boxfield",
        top: 371,
        rows: &[371],
    },
    RowGroup {
        model: "g_bbarrelsz01",
        top: 372,
        rows: &[372],
    },
    RowGroup {
        model: "g_bbarrelsz02",
        top: 373,
        rows: &[373],
    },
    RowGroup {
        model: "g_chakraz03",
        top: 374,
        rows: &[374],
    },
    RowGroup {
        model: "g_woodencasez01",
        top: 375,
        rows: &[375],
    },
    RowGroup {
        model: "g_woodencasez02",
        top: 376,
        rows: &[376],
    },
    RowGroup {
        model: "g_woodencasez03",
        top: 377,
        rows: &[377],
    },
    RowGroup {
        model: "g_woodencasez05",
        top: 378,
        rows: &[378],
    },
    RowGroup {
        model: "f_luce2",
        top: 635,
        rows: &[633, 634, 635],
    },
];
